### ISSUE TITLE
Implementation checklist R packages

### ISSUE THREAD

**Issue by gvegayon** [EpiForeSITE/software#2]
- [ ] Lives on GitHub (or equivalent).
- [ ] Functions are documented `roxygen2` (with md support).
- [ ] Has at least one vignette using `rmarkdown`.
- [ ] Has continuous integration in place for: (a) running `R CMD check` on multiple system configurations, (b) creating te website, and (c) pre-commit. 

## Optionals

- [ ] Development is carried out using pre-commit.
